version: '3'

services:
  # nginx:
  #   depends_on:
  #     - server
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - '3050:80'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: client
    image: ahaf82/client
    container_name: client
    stdin_open: true
    domainname: z-camp
    ports:
      - "3000:3000"
    networks:
      - training-plan
    depends_on: 
      - server
    # volumes:
    #    - /app/node_modules
    #    - .:/client/app

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    # image: server
    image: ahaf82/server
    container_name: server
    domainname: z-camp
    restart: always
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=cluster0.wucbb.mongodb.net
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "5050:5050"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    networks:
      - training-plan 
    depends_on: 
      - db
    networks:
      - training-plan
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    domainname: z-camp
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - training-plan
      
networks:
  training-plan:
    driver: bridge

volumes:
  dbdata:
  node_modules: